baseurl = "http://ramitsurana.github.io/writing"
copyright = "All rights reserved - 2016"
disqusshortname = "vjeantet"
languagecode = "en-EN"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Ramit Surana"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/ramitsurana"
weight = 100
[[menu.main]]
name = "Twitter timeline"
url = "https://twitter.com/ramitsurana"
weight = 101
[[menu.main]]
name = "Linkedin timeline"
url = "https://linkedin.com/in/ramitsurana"
weight = 102
[[menu.main]]
name = "Keybase (secure msg)"
pre = "<h3>Contact me</h3>"
url = "https://Keybase.io/vjeantet"
weight = 109
[params]
author = "Ramit Surana"
authorlocation = "Jaipur, India"
authorwebsite = "http://ramitsurana.github.io"
bio = " Open source enthusiast."
cover = "images/cover_polenord.jpg"
description = "Whatever the mind of man can conceive and believe, it can achieve."
githubName = "ramitsurana"
googleAnalyticsUserID = ""
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "ramitsurana"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
